[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "project_snapshot_generator"
version = "0.1.1"
description = "Generates a complete textual snapshot of a project's source code and directory structure for LLM consumption."
readme = "README.md"
authors = [{name = "Fernando Pujaico Rivera", email = "fernando.pujaico.rivera@gmail.com"}]
maintainers = [{name = "Fernando Pujaico Rivera", email = "fernando.pujaico.rivera@gmail.com"}]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only WITH Classpath-Exception-2.0 OR BSD-3-Clause"
license-files = ["LICENSE"]
keywords = ["llm", "snapshot"]
dependencies = [
    "PyQt5"
]

[project.urls]
"Bug Reports" = "https://github.com/trucomanx/ProjectSnapshotGenerator/issues"
"Funding" = "https://trucomanx.github.io/en/funding.html"
"Documentation" = "https://github.com/trucomanx/ProjectSnapshotGenerator/tree/main/doc"
"Source" = "https://github.com/trucomanx/ProjectSnapshotGenerator"

[project.scripts]
"project-snapshot-generator" = "project_snapshot_generator.program_project:main"
"file-snapshot-generator" = "project_snapshot_generator.program_file:main"

[tool.setuptools]
packages = ["project_snapshot_generator", "project_snapshot_generator.modules"]

[tool.setuptools.package-data]
"project_snapshot_generator" = ["icons/logo.png"]
